from datetime import datetime

# 2 races + results
raw_sample_data = [
        # test_name 2012
        {
            'stats': {
                'classification': 'WT',
                'date': datetime(2012, 3, 17, 0, 0),
                'distance': '298',
                'heigh_meters': '2380',
                'speed': '42.632 km/h',
                'startlist_score': '1079',
                'temp': '',
                'won_how': 'Sprint of small group',
                "name": "test_name",
                "year": "2012"
            },
            'results': [
                {'name': 'simon-gerrans', 'rank': '1', 'age': '31', 'team': 'Orica GreenEDGE', 'specialty': 'Classic', 'pcs_points': '275', 'uci_points': '100'},
                {'name': 'fabian-cancellara', 'rank': '2', 'age': '30', 'team': 'RadioShack - Nissan', 'specialty': 'TT', 'pcs_points': '200', 'uci_points': '80'},
                {'name': 'simon-gerrans', 'rank': '3', 'age': '31', 'team': 'Orica GreenEDGE', 'specialty': 'Classic', 'pcs_points': '275', 'uci_points': '100'},  # duplicate
            ]
        },
        # e3-harelbeke 2019    
        {
            'results': [
                {'age': '29',
                'name': 'mathieu-van-der-poel',
                'pcs_points': '225',
                'rank': '1',
                'specialty': 'Classic',
                'team': 'Alpecin - Deceuninck',
                'uci_points': '400'},
                {'age': '31',
                'name': 'jasper-stuyven',
                'pcs_points': '150',
                'rank': '2',
                'specialty': 'Classic',
                'team': 'Lidl - Trek',
                'uci_points': '320'
                }
            ],
            'stats': {
                'classification': '1.UWT',
                'date': datetime(2024, 3, 22, 0, 0),
                'distance': '207.6',
                'heigh_meters': '2019',
                'name': 'e3-harelbeke',
                'speed': '44.571 km/h',
                'startlist_score': '734',
                'temp': '11 °C',
                'won_how': '43.7 km solo',
                'year': '2024'
            }
        },
        # gp-quebec 2024
        {
            'results': [
                {'age': '33',
                'name': 'michael-matthews',
                'pcs_points': '225',
                'rank': '1',
                'specialty': 'Classic',
                'team': 'Team Jayco AlUla',
                'uci_points': '500'},
                {'age': '24',
                'name': 'biniam-girmay',
                'pcs_points': '150',
                'rank': '2',
                'specialty': 'Classic',
                'team': 'Intermarché - Wanty',
                'uci_points': '400'
                }
            ],
            'stats': {
                'classification': '1.UWT',
                'date': datetime(2024, 9, 13, 0, 0),
                'distance': '201.6',
                'heigh_meters': '2508',
                'name': 'gp-quebec',
                'speed': '42.353 km/h',
                'startlist_score': '884',
                'temp': '24 °C',
                'won_how': 'Sprint of large group',
                'year': '2024'
            }
        },
        # liege-bastogne-liege 2017
        {
            'results': [
                {'age': '36',
                'name': 'alejandro-valverde',
                'pcs_points': '275',
                'rank': '1',
                'specialty': 'Climber',
                'team': 'Movistar Team',
                'uci_points': '500'},
                {'age': '30',
                'name': 'dan-martin',
                'pcs_points': '200',
                'rank': '2',
                'specialty': 'Climber',
                'team': 'Quick-Step Floors',
                'uci_points': '400'}
            ],
            'stats': {
                'classification': '1.UWT',
                'date': datetime(2017, 4, 23, 0, 0),
                'distance': '258',
                'heigh_meters': '4187',
                'name': 'liege-bastogne-liege',
                'speed': '40.27 km/h',
                'startlist_score': '998',
                'temp': '',
                'won_how': 'Sprint of small group',
                'year': '2017'
            }
        },
        # eschborn-frankfurt 2023
        {
            'results': [
                {'age': '28',
                'name': 'soren-kragh-andersen',
                'pcs_points': '225',
                'rank': '1',
                'specialty': 'TT',
                'team': 'Alpecin - Deceuninck',
                'uci_points': '300'},
                {'age': '31',
                'name': 'patrick-konrad',
                'pcs_points': '150',
                'rank': '2',
                'specialty': 'Climber',
                'team': 'Bora - Hansgrohe',
                'uci_points': '250'}
            ],
            'stats': {
                'classification': '1.UWT',
                'date': datetime(2023, 5, 1, 0, 0),
                'distance': '203.8',
                'heigh_meters': '2933',
                'name': 'eschborn-frankfurt',
                'speed': '41.956 km/h',
                'startlist_score': '423',
                'temp': '17 °C',
                'won_how': 'Sprint of 10 riders',
                'year': '2023'
            }
        },
        # san-sebastian 2014
        {
            'results': [
                {'age': '34',
                'name': 'alejandro-valverde',
                'pcs_points': '225',
                'rank': '1',
                'specialty': 'Climber',
                'team': 'Movistar Team',
                'uci_points': '80'},
                {'age': '27',
                'name': 'bauke-mollema',
                'pcs_points': '150',
                'rank': '2',
                'specialty': 'Climber',
                'team': 'Belkin-Pro Cycling Team',
                'uci_points': '60'}
            ],
            'stats': {
                'classification': '1.UWT',
                'date': datetime(2014, 8, 2, 0, 0),
                'distance': '219.2',
                'heigh_meters': '3796',
                'name': 'san-sebastian',
                'speed': '39.712 km/h',
                'startlist_score': '741',
                'temp': '',
                'won_how': '4 km solo',
                'year': '2014'
            }
        }
    ]

raw_sample_data_cleaned = [{'results': [{'age': '31',
              'name': 'maxim-iglinskiy',
              'pcs_pts': '275',
              'race_id': 'R5cedb295',
              'rank': '1',
              'specialty': 'Classic',
              'team': 'Astana Pro Team',
              'uci_pts': '100'},
             {'age': '27',
              'name': 'vincenzo-nibali',
              'pcs_pts': '200',
              'race_id': 'R5cedb295',
              'rank': '2',
              'specialty': 'GC',
              'team': 'Liquigas - Cannondale',
              'uci_pts': '80'}],
 'stats': {'avg_speed_kmh': '38.26',
           'classification': 'WT',
           'date': '2012-04-22',
           'distance_km': '257.5',
           'elevation_m': '4325',
           'name': 'liege-bastogne-liege',
           'race_id': 'R5cedb295',
           'stage': None,
           'startlist_score': '1189',
           'temp': None,
           'won_how': '1 km solo',
           'year': '2012'}},
{'results': [{'age': '30',
              'name': 'dylan-teuns',
              'pcs_pts': '225',
              'race_id': 'R5cedb295',
              'rank': '1',
              'specialty': 'GC',
              'team': 'Bahrain - Victorious',
              'uci_pts': '400'},
             {'age': '41',
              'name': 'alejandro-valverde',
              'pcs_pts': '150',
              'race_id': 'R5cedb295',
              'rank': '2',
              'specialty': 'Climber',
              'team': 'Movistar Team',
              'uci_pts': '320'}],
 'stats': {'avg_speed_kmh': '42.97',
           'classification': '1.UWT',
           'date': '2022-04-20',
           'distance_km': '202.1',
           'elevation_m': '3160',
           'name': 'la-fleche-wallonne',
           'race_id': 'R5cedb295',
           'stage': None,
           'startlist_score': '971',
           'temp': '14',
           'won_how': 'Sprint à deux',
           'year': '2022'}},
{'results': [{'age': '26',
              'name': 'johan-esteban-chaves',
              'pcs_pts': '275',
              'race_id': 'R5cedb295',
              'rank': '1',
              'specialty': 'Climber',
              'team': 'ORICA-BikeExchange',
              'uci_pts': '500'},
             {'age': '27',
              'name': 'diego-rosa',
              'pcs_pts': '200',
              'race_id': 'R5cedb295',
              'rank': '2',
              'specialty': 'Climber',
              'team': 'Astana Pro Team',
              'uci_pts': '400'}],
 'stats': {'avg_speed_kmh': '37.25',
           'classification': '1.UWT',
           'date': '2016-10-01',
           'distance_km': '240',
           'elevation_m': '5236',
           'name': 'il-lombardia',
           'race_id': 'R5cedb295',
           'stage': None,
           'startlist_score': '1191',
           'temp': None,
           'won_how': 'Sprint of small group',
           'year': '2016'}},
{'results': [{'age': '29',
              'name': 'tim-merlier',
              'pcs_pts': '225',
              'race_id': 'R5cedb295',
              'rank': '1',
              'specialty': 'Sprint',
              'team': 'Alpecin - Fenix',
              'uci_pts': '300'},
             {'age': '28',
              'name': 'dylan-groenewegen',
              'pcs_pts': '150',
              'race_id': 'R5cedb295',
              'rank': '2',
              'specialty': 'Sprint',
              'team': 'Team BikeExchange - Jayco',
              'uci_pts': '250'}],
 'stats': {'avg_speed_kmh': '43.664',
           'classification': '1.UWT',
           'date': '2022-03-23',
           'distance_km': '207.9',
           'elevation_m': '246',
           'name': 'classic-brugge-de-panne',
           'race_id': 'R5cedb295',
           'stage': None,
           'startlist_score': '457',
           'temp': None,
           'won_how': 'Sprint of large group',
           'year': '2022'}},
{'results': [{'age': '28',
              'name': 'philippe-gilbert',
              'pcs_pts': '225',
              'race_id': 'R5cedb295',
              'rank': '1',
              'specialty': 'Classic',
              'team': 'Omega Pharma-Lotto',
              'uci_pts': '80'},
             {'age': '31',
              'name': 'joaquim-rodriguez',
              'pcs_pts': '150',
              'race_id': 'R5cedb295',
              'rank': '2',
              'specialty': 'Climber',
              'team': 'Team Katusha',
              'uci_pts': '60'}],
 'stats': {'avg_speed_kmh': '40.888',
           'classification': 'WT',
           'date': '2011-04-20',
           'distance_km': '201',
           'elevation_m': '',
           'name': 'la-fleche-wallonne',
           'race_id': 'R5cedb295',
           'stage': None,
           'startlist_score': '1109',
           'temp': None,
           'won_how': '0.3 km solo',
           'year': '2011'}}]